services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - rabbitmq
      - face-search
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  payment:
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: npm run start:payment 
    env_file:
      - ./apps/payment/.env
    depends_on:
      - rabbitmq
      - gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  face-search:
    image: face-search
    env_file:
      - ./apps/face-search/.env
    ports:
      - "50052:50052"
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
